In [15]:
import pandas as pd 
import numpy as np 

insurance = pd.read_csv("car_insurance.csv")

# Ccommençons par l'analyse exploratoire du dataset 

insurance.head()

       id  age  gender  ... duis past_accidents outcome
0  569520    3       0  ...    0              0     0.0
1  750365    0       1  ...    0              0     1.0
2  199901    0       0  ...    0              0     0.0
3  478866    0       1  ...    0              0     0.0
4  731664    1       1  ...    0              1     1.0

[5 rows x 18 columns]

In [16]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   10000 non-null  int64
 1   age                  10000 non-null  int64
 2   gender               10000 non-null  int64
 3   driving_experience   10000 non-null  object
 4   education            10000 non-null  object
 5   income               10000 non-null  object
 6   credit_score         9018 non-null   float64
 7   vehicle_ownership    10000 non-null  float64
 8   vehicle_year         10000 non-null  object
 9   married              10000 non-null  float64
 10  children             10000 non-null  float64
 11  postal_code          10000 non-null  int64
 12  annual_mileage       9043 non-null   float64
 13  vehicle_type         10000 non-null  object
 14  speeding_violations  10000 non-null  int64
 15  duis                 10000 non-null  int64
 16  past_accidents       10000 non-null  int64
 17  outcome              10000 non-null  float64
dtypes: float64(6), int64(7), object(5)
memory usage: 1.4+ MB

In [17]:
# recherche de valeurs manquantes 
insurance.isna().sum()

id                       0
age                      0
gender                   0
driving_experience       0
education                0
income                   0
credit_score           982
vehicle_ownership        0
vehicle_year             0
married                  0
children                 0
postal_code              0
annual_mileage         957
vehicle_type             0
speeding_violations      0
duis                     0
past_accidents           0
outcome                  0
dtype: int64

In [18]:
# on constate qu'il y'a respectivement  982 et 957 lignes vides pour les colonnes credit_score et annual_mileage.
# on constate que le nombre d'lélémént manquant dépasse les 5% , il faudra donc éviter les supressions .
# Et utiliser la méthode d'imputation soit par la médiane ou par la moyenne

In [19]:
#regardons d'abord l'existence de valeurs abérrantes 
insurance.describe(include ="all")

                   id           age  ...  past_accidents       outcome
count    10000.000000  10000.000000  ...    10000.000000  10000.000000
unique            NaN           NaN  ...             NaN           NaN
top               NaN           NaN  ...             NaN           NaN
freq              NaN           NaN  ...             NaN           NaN
mean    500521.906800      1.489500  ...        1.056300      0.313300
std     290030.768758      1.025278  ...        1.652454      0.463858
min        101.000000      0.000000  ...        0.000000      0.000000
25%     249638.500000      1.000000  ...        0.000000      0.000000
50%     501777.000000      1.000000  ...        0.000000      0.000000
75%     753974.500000      2.000000  ...        2.000000      1.000000
max     999976.000000      3.000000  ...       15.000000      1.000000

[11 rows x 18 columns]

In [20]:
# l'ecart n'est pas trop significative , on peut donc utiliser l'imputation par la moyeninsurance.info()ne 
#Solution

insurance["credit_score"]=insurance["credit_score"].fillna(insurance["credit_score"].mean())
insurance["annual_mileage"]=insurance["annual_mileage"].fillna(insurance["annual_mileage"].mean())

In [21]:
#verification après le règlement des valeurs manquantes 
insurance.isna().sum()

id                     0
age                    0
gender                 0
driving_experience     0
education              0
income                 0
credit_score           0
vehicle_ownership      0
vehicle_year           0
married                0
children               0
postal_code            0
annual_mileage         0
vehicle_type           0
speeding_violations    0
duis                   0
past_accidents         0
outcome                0
dtype: int64

In [22]:
# Symbole parasite dans la colonne "driving_experience"
insurance["driving_experience"] = insurance["driving_experience"].astype(str).str.replace("y","",regex=False)

In [23]:
insurance.describe(include="all")

                   id           age  ...  past_accidents       outcome
count    10000.000000  10000.000000  ...    10000.000000  10000.000000
unique            NaN           NaN  ...             NaN           NaN
top               NaN           NaN  ...             NaN           NaN
freq              NaN           NaN  ...             NaN           NaN
mean    500521.906800      1.489500  ...        1.056300      0.313300
std     290030.768758      1.025278  ...        1.652454      0.463858
min        101.000000      0.000000  ...        0.000000      0.000000
25%     249638.500000      1.000000  ...        0.000000      0.000000
50%     501777.000000      1.000000  ...        0.000000      0.000000
75%     753974.500000      2.000000  ...        2.000000      1.000000
max     999976.000000      3.000000  ...       15.000000      1.000000

[11 rows x 18 columns]

In [24]:
#Sépaation des données caractéristiques(X) et de la cible (y)

X= insurance.drop(columns="outcome")
y= insurance["outcome"]

In [25]:
#Séparation des données d'entrainement et de test 
from sklearn.model_selection import train_test_split

X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42, stratify=y)

In [26]:
from sklearn.model_selection import train_test_split

# 1. Réinitialiser la séparation Train/Test pour récupérer les vraies chaînes de caractères
X = insurance.drop(columns=["id", "outcome"])
y = insurance["outcome"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Définition des dictionnaires d'encodage ordinal
driving_map = {"0-9": 0, "10-19": 1, "20-29": 2, "30+": 3}
education_map = {"none": 0, "high school": 1, "university": 2}
income_map = {"poverty": 0, "working class": 1, "middle class": 2, "upper class": 3}
year_map = {"before 2015": 0, "after 2015": 1}

# 3. Application du mappage sur X_train et X_test
X_train["driving_experience"] = X_train["driving_experience"].map(driving_map)
X_test["driving_experience"] = X_test["driving_experience"].map(driving_map)

X_train["education"] = X_train["education"].map(education_map)
X_test["education"] = X_test["education"].map(education_map)

X_train["income"] = X_train["income"].map(income_map)
X_test["income"] = X_test["income"].map(income_map)

X_train["vehicle_year"] = X_train["vehicle_year"].map(year_map)
X_test["vehicle_year"] = X_test["vehicle_year"].map(year_map)

# 4. Encodage One-Hot pour vehicle_type
X_train = pd.get_dummies(X_train, columns=["vehicle_type"], drop_first=True, dtype=int)
X_test = pd.get_dummies(X_test, columns=["vehicle_type"], drop_first=True, dtype=int)

# 5. Vérification des NaNs
print("Nombre de NaNs dans X_train après encodage :")
print(X_train.isna().sum())

Nombre de NaNs dans X_train après encodage :
age                        0
gender                     0
driving_experience         0
education                  0
income                     0
credit_score               0
vehicle_ownership          0
vehicle_year               0
married                    0
children                   0
postal_code                0
annual_mileage             0
speeding_violations        0
duis                       0
past_accidents             0
vehicle_type_sports car    0
dtype: int64

In [27]:
# Etape de la normalisation des données (à la meme échelle)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Appliquer uniquement sur les colonnes numériques continues
num_cols = ["credit_score", "annual_mileage", "speeding_violations", "duis", "past_accidents"]

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# 1. Instancier le modèle de base
model = LogisticRegression(max_iter=1000, random_state=42)

# 2. Grille avec combinaisons strictement compatibles
param_grid = [
    {
        'solver': ['lbfgs', 'newton-cg'],
        'penalty': ['l2', None],
        'C': [0.01, 0.1, 1, 10]
    },
    {
        'solver': ['liblinear'],
        'penalty': ['l1', 'l2'],
        'C': [0.01, 0.1, 1, 10]
    },
    {
        'solver': ['saga'],
        'penalty': ['l1', 'l2', 'elasticnet', None],
        'C': [0.01, 0.1, 1, 10],
        'l1_ratio': [0.5]  # Nécessaire uniquement pour elasticnet
    }
]

# 3. Configurer GridSearchCV (5 folds)
grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    error_score='raise'  # Optionnel : pour afficher la trace exacte si un fit échoue
)

# 4. Exécuter la recherche et la validation croisée
grid_search.fit(X_train, y_train)

# Affichage des résultats d'optimisation
print(f"Meilleurs hyperparamètres : {grid_search.best_params_}")
print(f"Meilleure Accuracy en CV : {grid_search.best_score_:.4f}")

# 5. Évaluation finale sur X_test
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

print("\n--- Rapport final sur le jeu de test ---")
print(classification_report(y_test, y_pred))

Meilleurs hyperparamètres : {'C': 0.01, 'penalty': None, 'solver': 'newton-cg'}
Meilleure Accuracy en CV : 0.8438

--- Rapport final sur le jeu de test ---
              precision    recall  f1-score   support

         0.0       0.87      0.91      0.89      1367
         1.0       0.78      0.70      0.73       633

    accuracy                           0.84      2000
   macro avg       0.82      0.80      0.81      2000
weighted avg       0.84      0.84      0.84      2000